### PR TITLE
Use compiler analysis to check for syntax errors

### PR DESCRIPTION
**Pull request by knutwannheden**
Use `AnalyzerWithCompilerReport` to find syntax errors and return a `ParseError` from parser when any errors are found.

### CODE REVIEW

**Comment by knutwannheden** [comment]
@traceyyoshima This is still work in progress. As you can see there are still failing tests (all related to CRLF?) and probably needs some more work. I just thought I would share this.

**Comment by traceyyoshima** [comment]
> @traceyyoshima This is still work in progress. As you can see there are still failing tests (all related to CRLF?) and probably needs some more work. I just thought I would share this.

I haven't looked into the error analysis, but I noticed you mentioned CRLF.
The PSI treats CR of `\r` as a bad character, though I wouldn't expect the analysis to fail.
There may be a missing compiler configuration since Kotlin has to compile code with CRLF.

**Review by traceyyoshima — COMMENTED** [review]
Added a comment with info about CRLF.
I'll check if there are any missing compiler configurations when/if I have time.

**Comment by traceyyoshima** [comment]
Closing. Added the syntax analysis separately -- it works appropriately now that we filter out CR characters.

**Pull request closed without merging**
